import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>API</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#000000] to-[#040852]">
        <div className="flex animate-bounce items-center justify-center text-5xl tracking-wider text-amber-400">
          Hello world!
        </div>
      </main>
    </>
  );
}
